### PR TITLE
Improve compatibility with other frameworks and future OMF.

### PR DESCRIPTION
**Pull request by bobthecow**
- Extract functions from `init.fish` to take advantage of autoloading.
- Move initialization to `init.fish`.
- Initialize immediately, rather than waiting for an event.
- Only add missing paths during init.

### CODE REVIEW

**Comment by attilagyorffy** [comment]
I've just reinstalled my machine and set up omf. The current master doesn't seem to load the rbenv plugin anymore, having manually deployed @bobthecow's patches solved the issue. Could we rebase the patch, sort out the conflicts and merge into plugin-rbenv master please?

I'm sure I am not and won't be the only person who's missing this, alternatively if @bobthecow doesn't have the time to deal with this then I'm more than happy to create a separate patch myself.

**Comment by attilagyorffy** [comment]
btw i am on fish 2.3.0 and omf 2.

**Comment by bobthecow** [comment]
@liquid This PR has been rebased and updated. Mind trying it out to see if it still sorts your issues with 2.3.0?

**Comment by attilagyorffy** [comment]
@bobthecow first of all thanks for the quick response, I really appreciate it. Then again I couldn't find a way to install your package using the `fishier` branch as when passing a URL to `omf install` I seem to be getting an error:

```
omf install rbenv https://github.com/bobthecow/plugin-rbenv/tree/fishier
Installing package rbenv
✔ package rbenv successfully installed.
Installing package fishier
fatal: repository 'https://github.com/bobthecow/plugin-rbenv/tree/fishier/' not found
```

Is this supported anyway? Alternatively I could try passing in the master path and manually checking out your branch with git.

**Comment by attilagyorffy** [comment]
@bobthecow I've installed via a URL and manually checked out the `fishier` branch. This seems to work just fine on 2.3.0.

**Comment by bobthecow** [comment]
:+1: thanks for checking :)

**Pull request merged**
