### PR TITLE
Fix warning about absence of rbenv

### PR DESCRIPTION
**Pull request by khmm12**
It seems, I forgot about warning. It's time to fix it. 
Also I've changed color of message to error, I think it's more visibly.

### CODE REVIEW

**Comment by bobthecow** [comment]
:+1:

we should prolly change the color back to normal before returning to keep from leaking.

**Comment by khmm12** [comment]
Good remark. I updated PR.

**Comment by bobthecow** [comment]
Oh, sorry, it looks like this was fixed in #19, just a bit before you added your fix. I'll close this one since it's a dupe :)

**Comment by khmm12** [comment]
Not exactly, without this fix script throws an error instead of showing a message by same reasons as in https://github.com/oh-my-fish/plugin-rbenv/pull/19 😉

P.S. I know that I'm a little bit late 😀

**Pull request closed without merging**
